# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'index.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import os

class Ui_Form(object):


    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1028, 620)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(20, 30, 236, 401))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.androidstudio = QtWidgets.QCheckBox(self.groupBox)
        self.androidstudio.setObjectName("androidstudio")
        self.verticalLayout.addWidget(self.androidstudio)
        self.pycharm = QtWidgets.QCheckBox(self.groupBox)
        self.pycharm.setObjectName("pycharm")
        self.verticalLayout.addWidget(self.pycharm)
        self.phpstorm = QtWidgets.QCheckBox(self.groupBox)
        self.phpstorm.setObjectName("phpstorm")
        self.verticalLayout.addWidget(self.phpstorm)
        self.anaconda = QtWidgets.QCheckBox(self.groupBox)
        self.anaconda.setObjectName("anaconda")
        self.verticalLayout.addWidget(self.anaconda)
        self.sublimetext = QtWidgets.QCheckBox(self.groupBox)
        self.sublimetext.setObjectName("sublimetext")
        self.verticalLayout.addWidget(self.sublimetext)
        self.atomtexteditor = QtWidgets.QCheckBox(self.groupBox)
        self.atomtexteditor.setObjectName("atomtexteditor")
        self.verticalLayout.addWidget(self.atomtexteditor)
        self.eclipse = QtWidgets.QCheckBox(self.groupBox)
        self.eclipse.setObjectName("eclipse")
        self.verticalLayout.addWidget(self.eclipse)

        self.vim = QtWidgets.QCheckBox(self.groupBox)
        self.vim.setObjectName("vim")
        self.verticalLayout.addWidget(self.vim)
        self.git = QtWidgets.QCheckBox(self.groupBox)
        self.git.setObjectName("git")
        self.verticalLayout.addWidget(self.git)
        self.filezilla = QtWidgets.QCheckBox(self.groupBox)
        self.filezilla.setObjectName("filezilla")
        self.verticalLayout.addWidget(self.filezilla)
        self.ardiunoide = QtWidgets.QCheckBox(self.groupBox)
        self.ardiunoide.setObjectName("ardiunoide")
        self.verticalLayout.addWidget(self.ardiunoide)
        self.monodevelop = QtWidgets.QCheckBox(self.groupBox)
        self.monodevelop.setObjectName("monodevelop")
        self.verticalLayout.addWidget(self.monodevelop)
        self.intellijidea = QtWidgets.QCheckBox(self.groupBox)
        self.intellijidea.setObjectName("intellijidea")
        self.verticalLayout.addWidget(self.intellijidea)
        self.visualstudiocode = QtWidgets.QCheckBox(self.groupBox)
        self.visualstudiocode.setObjectName("visualstudiocode")
        self.verticalLayout.addWidget(self.visualstudiocode)
        self.netbeans = QtWidgets.QCheckBox(self.groupBox)
        self.netbeans.setObjectName("netbeans")
        self.verticalLayout.addWidget(self.netbeans)
        self.mysqlworkbench = QtWidgets.QCheckBox(self.groupBox)
        self.mysqlworkbench.setObjectName("mysqlworkbench")
        self.verticalLayout.addWidget(self.mysqlworkbench)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(290, 30, 166, 451))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ulauncher = QtWidgets.QCheckBox(self.groupBox_2)
        self.ulauncher.setObjectName("ulauncher")
        self.verticalLayout_2.addWidget(self.ulauncher)
        self.opera = QtWidgets.QCheckBox(self.groupBox_2)
        self.opera.setObjectName("opera")
        self.verticalLayout_2.addWidget(self.opera)
        self.pepperflash = QtWidgets.QCheckBox(self.groupBox_2)
        self.pepperflash.setObjectName("pepperflash")
        self.verticalLayout_2.addWidget(self.pepperflash)
        self.conky = QtWidgets.QCheckBox(self.groupBox_2)
        self.conky.setObjectName("conky")
        self.verticalLayout_2.addWidget(self.conky)
        self.whatsappdesktop = QtWidgets.QCheckBox(self.groupBox_2)
        self.whatsappdesktop.setObjectName("whatsappdesktop")
        self.verticalLayout_2.addWidget(self.whatsappdesktop)
        self.teamviewer = QtWidgets.QCheckBox(self.groupBox_2)
        self.teamviewer.setObjectName("teamviewer")
        self.verticalLayout_2.addWidget(self.teamviewer)
        self.skype = QtWidgets.QCheckBox(self.groupBox_2)
        self.skype.setObjectName("skype")
        self.verticalLayout_2.addWidget(self.skype)
        self.mega = QtWidgets.QCheckBox(self.groupBox_2)
        self.mega.setObjectName("mega")
        self.verticalLayout_2.addWidget(self.mega)
        self.bleachbit = QtWidgets.QCheckBox(self.groupBox_2)
        self.bleachbit.setObjectName("bleachbit")
        self.verticalLayout_2.addWidget(self.bleachbit)
        self.mintstick = QtWidgets.QCheckBox(self.groupBox_2)
        self.mintstick.setObjectName("mintstick")
        self.verticalLayout_2.addWidget(self.mintstick)
        self.virtualbox = QtWidgets.QCheckBox(self.groupBox_2)
        self.virtualbox.setObjectName("virtualbox")
        self.verticalLayout_2.addWidget(self.virtualbox)
        self.plank = QtWidgets.QCheckBox(self.groupBox_2)
        self.plank.setObjectName("plank")
        self.verticalLayout_2.addWidget(self.plank)
        self.krita = QtWidgets.QCheckBox(self.groupBox_2)
        self.krita.setObjectName("krita")
        self.verticalLayout_2.addWidget(self.krita)
        self.redshift = QtWidgets.QCheckBox(self.groupBox_2)
        self.redshift.setObjectName("redshift")
        self.verticalLayout_2.addWidget(self.redshift)
        self.vokoscreen = QtWidgets.QCheckBox(self.groupBox_2)
        self.vokoscreen.setObjectName("vokoscreen")
        self.verticalLayout_2.addWidget(self.vokoscreen)
        self.winusb = QtWidgets.QCheckBox(self.groupBox_2)
        self.winusb.setObjectName("winusb")
        self.verticalLayout_2.addWidget(self.winusb)
        self.wine = QtWidgets.QCheckBox(self.groupBox_2)
        self.wine.setObjectName("wine")
        self.verticalLayout_2.addWidget(self.wine)
        self.playonlinux = QtWidgets.QCheckBox(self.groupBox_2)
        self.playonlinux.setObjectName("playonlinux")
        self.verticalLayout_2.addWidget(self.playonlinux)
        self.nylasmail = QtWidgets.QCheckBox(self.groupBox_2)
        self.nylasmail.setObjectName("nylasmail")
        self.verticalLayout_2.addWidget(self.nylasmail)
        self.chrome = QtWidgets.QCheckBox(self.groupBox_2)
        self.chrome.setObjectName("chrome")
        self.verticalLayout_2.addWidget(self.chrome)
        self.terminator = QtWidgets.QCheckBox(self.groupBox_2)
        self.terminator.setObjectName("terminator")
        self.verticalLayout_2.addWidget(self.terminator)
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setGeometry(QtCore.QRect(510, 30, 173, 86))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.spotify = QtWidgets.QCheckBox(self.groupBox_3)
        self.spotify.setObjectName("spotify")
        self.verticalLayout_4.addWidget(self.spotify)
        self.numixcircletheme = QtWidgets.QCheckBox(self.groupBox_3)
        self.numixcircletheme.setObjectName("numixcircletheme")
        self.verticalLayout_4.addWidget(self.numixcircletheme)
        self.groupBox_4 = QtWidgets.QGroupBox(Form)
        self.groupBox_4.setGeometry(QtCore.QRect(450, 500, 150, 81))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.yukle = QtWidgets.QPushButton(self.groupBox_4)
        self.yukle.setObjectName("yukle")
        self.horizontalLayout.addWidget(self.yukle)
        self.groupBox_5 = QtWidgets.QGroupBox(Form)
        self.groupBox_5.setGeometry(QtCore.QRect(780, 30, 241, 121))
        self.groupBox_5.setWhatsThis("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.grubguncellemesi = QtWidgets.QCheckBox(self.groupBox_5)
        self.grubguncellemesi.setObjectName("grubguncellemesi")
        self.verticalLayout_3.addWidget(self.grubguncellemesi)
        self.ssdtrim = QtWidgets.QCheckBox(self.groupBox_5)
        self.ssdtrim.setObjectName("ssdtrim")
        self.verticalLayout_3.addWidget(self.ssdtrim)
        self.preload = QtWidgets.QCheckBox(self.groupBox_5)
        self.preload.setObjectName("preload")
        self.verticalLayout_3.addWidget(self.preload)

        self.yukle.clicked.connect(self.tiklandi)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)



    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "After From Manjaro"))
        self.groupBox.setTitle(_translate("Form", "Geliştiriciler(Developers)"))
        self.androidstudio.setText(_translate("Form", "Android Studio"))
        self.pycharm.setText(_translate("Form", "PyCharm"))
        self.phpstorm.setText(_translate("Form", "PhpStorm"))
        self.anaconda.setText(_translate("Form", "Anaconda"))
        self.sublimetext.setText(_translate("Form", "Sublime Text"))
        self.atomtexteditor.setText(_translate("Form", "Atom Text Editor"))
        self.eclipse.setText(_translate("Form", "Eclipse"))

        self.vim.setText(_translate("Form", "Vim"))
        self.git.setText(_translate("Form", "Git"))
        self.filezilla.setText(_translate("Form", "Filezilla"))
        self.ardiunoide.setText(_translate("Form", "Ardiuno IDE"))
        self.monodevelop.setText(_translate("Form", "Mono Develop"))
        self.intellijidea.setText(_translate("Form", "Intellij Idea"))
        self.visualstudiocode.setText(_translate("Form", "Visual Studio Code"))
        self.netbeans.setText(_translate("Form", "NetBeans"))
        self.mysqlworkbench.setText(_translate("Form", "Mysql Workbench"))
        self.groupBox_2.setTitle(_translate("Form", "Araçlar(Tools)"))
        self.ulauncher.setText(_translate("Form", "Ulauncher"))
        self.opera.setText(_translate("Form", "Opera"))
        self.pepperflash.setText(_translate("Form", "Pepper Flash"))
        self.conky.setText(_translate("Form", "Conky"))
        self.whatsappdesktop.setText(_translate("Form", "Whatsapp Desktop"))
        self.teamviewer.setText(_translate("Form", "TeamViewer"))
        self.skype.setText(_translate("Form", "Skype"))
        self.mega.setText(_translate("Form", "Mega"))
        self.bleachbit.setText(_translate("Form", "BleachBit"))
        self.mintstick.setText(_translate("Form", "Mintstick"))
        self.virtualbox.setText(_translate("Form", "VirtualBox"))
        self.plank.setText(_translate("Form", "Plank"))
        self.krita.setText(_translate("Form", "Krita"))
        self.redshift.setText(_translate("Form", "Red Shift"))
        self.vokoscreen.setText(_translate("Form", "VokoScreen"))
        self.winusb.setText(_translate("Form", "WinUsb"))
        self.wine.setText(_translate("Form", "Wine"))
        self.playonlinux.setText(_translate("Form", "PlayOnLinux"))
        self.nylasmail.setText(_translate("Form", "Nylas Mail"))
        self.chrome.setText(_translate("Form", "Chrome"))
        self.terminator.setText(_translate("Form", "Terminatör"))
        self.groupBox_3.setTitle(_translate("Form", "Kişisel(Personal)"))
        self.spotify.setText(_translate("Form", "Spotify"))
        self.numixcircletheme.setText(_translate("Form", "Numix Circle Theme"))
        self.yukle.setText(_translate("Form", "Yükle"))
        self.groupBox_5.setTitle(_translate("Form", "Sistem(System)"))
        self.grubguncellemesi.setText(_translate("Form", "Grub Güncellemesi"))
        self.ssdtrim.setText(_translate("Form", "SSD Trim"))
        self.preload.setText(_translate("Form", "Preload"))

    def tiklandi(self):
        programlar = [self.androidstudio, self.pycharm, self.phpstorm, self.anaconda, self.sublimetext, self.atomtexteditor, self.eclipse,
                       self.vim, self.git, self.filezilla, self.ardiunoide, self.monodevelop, self.intellijidea,
                      self.visualstudiocode, self.netbeans, self.mysqlworkbench, self.ulauncher, self.opera, self.pepperflash, self.conky,
                      self.whatsappdesktop, self.teamviewer, self.skype, self.mega, self.bleachbit, self.mintstick, self.virtualbox, self.plank,
                      self.krita, self.redshift, self.vokoscreen, self.winusb, self.wine, self.playonlinux, self.nylasmail, self.chrome,
                      self.terminator, self.spotify, self.numixcircletheme, self.ssdtrim, self.preload,self.grubguncellemesi]

        cwd = os.getcwd()
        os.system("wget https://www.serkanozaydin.net/sh/baslangic.sh")
        os.system("sh "+cwd+"/baslangic.sh")
        progressBar=0
        for program in programlar:
            if program.isChecked():
                progressBar+=progressBar

        yuklenen=progressBar/100
        print(progressBar)
        print(yuklenen)
        for program in programlar:
            if program.isChecked():
                print("wget https://www.serkanozaydin.net/sh/"+program.text().replace(" ",""))
                os.system("wget https://www.serkanozaydin.net/sh/"+program.text().replace(" ","")+".sh")
                os.system("echo "+program.text()+" yükleniyor")
                os.system("sh "+cwd+"/"+program.text().replace(" ","")+".sh")


if __name__== "__main__":
    app=QtWidgets.QApplication(sys.argv)
    form=QtWidgets.QDialog()
    ui=Ui_Form()
    ui.setupUi(form)
    form.show()
    app.exec_()

